[package]
name = "dll_to_be_injected"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.windows]
version = "0.60.0"
features = [
    "Win32_Foundation",
    "Win32_System_SystemServices",
    "Win32_UI_WindowsAndMessaging"
]

[lib]
crate-type = ["cdylib"]
